version: "3"

services:
  bizmap_sb1:
    container_name: bizmap_sb1 
    build: .
    restart: always
    extra_hosts:
      - "cmap-was-dev:10.175.7.100"
      - "cmap-web-dev:10.175.7.99"
    volumes:
       - ../target/:/app
       - ../logs/:/logs
    network_mode: host